
esphome:
  name: esp32-tank

esp32:
  board: esp32dev
  framework:
    type: esp-idf

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO27
      mode: input
      inverted: true
    name: "Tank 0 Sensor"
    device_class: moisture

  - platform: gpio
    pin: 
      number: GPIO26
      mode: input
      inverted: true
    name: "Tank 1&2"
    device_class: moisture

web_server:
  port: 80

wifi:
  ssid: "DeaD.KilleR"
  password: "@Beatless!"
  use_address: 192.168.0.198
  fast_connect: true
  output_power: 8.5
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tank ESP Fallback Hotspot"
    password: "ktaZWM2kA1Dx"
  

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

captive_portal:
